(MERGED-IN-STAGING)(PR-447738) cyrus_sasl: fix build with gcc15
- add patch from fedora that combines merged upstream PR:
https://www.github.com/cyrusimap/cyrus-sasl/pull/869
with extra fixes for md5 that was removed upstream on master:
https://www.github.com/cyrusimap/cyrus-sasl/pull/789

Fixes build failure with gcc15:
```
md5.c:139:8: error: too many arguments to function 'MD5_memcpy'; expected 0, have 3
  139 |        MD5_memcpy
      |        ^~~~~~~~~~
  140 |        ((POINTER)&context->buffer[index], (POINTER)input, partLen); MD5Transform
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
md5.c:62:13: note: declared here
   62 | static void MD5_memcpy PROTO_LIST ((POINTER, POINTER, unsigned int));
      |             ^~~~~~~~~~
md5.c:140:69: error: too many arguments to function 'MD5Transform'; expected 0, have 2
  140 |        ((POINTER)&context->buffer[index], (POINTER)input, partLen); MD5Transform
      |                                                                     ^~~~~~~~~~~~
  141 |        (context->state, context->buffer);
      |         ~~~~~~~~~~~~~~
md5.c:57:13: note: declared here
   57 | static void MD5Transform PROTO_LIST ((UINT4 [4], const unsigned char [64]));
      |             ^~~~~~~~~~~~
```