vector: fix build with gcc15
- add "-std=gnu17" to `env.NIX_CFLAGS_COMPILE`

Upstream issues:
https://www.github.com/vectordotdev/vector/issues/22888
https://www.github.com/MaterializeInc/rust-krb5-src/issues/28

Fixes build failure with gcc15:
```
error: failed to run custom build command for `krb5-src v0.3.2+1.19.2`
Caused by:
process didn't exit successfully:
`/build/source/target/release/build/krb5-src-445c226a4d176db5/build-script-build`
(exit status: 101)
...
/build/vector-0.50.0-vendor/krb5-src-0.3.2+1.19.2/krb5/src/lib/rpc/auth_none.c:
In function 'authnone_wrap':
/build/vector-0.50.0-vendor/krb5-src-0.3.2+1.19.2/krb5/src/lib/rpc/auth_none.c:146:18:
error: too many arguments to function 'xfunc'; expected 0, have 2
  146 |         return ((*xfunc)(xdrs, xwhere));
      |                 ~^~~~~~~ ~~~~
....
```