cdrtools: fix build with gcc15
- add `-std=gnu17` to `NIX_CFLAGS_COMPILE`, upstream had no updates
since 2017

Fixes build failure with gcc15:
```
avoffset.c:67:24: error: passing argument 2 of 'signal' from incompatible
pointer type [-Wincompatible-pointer-types]
   67 |         signal(SIGBUS, handler);
      |                        ^~~~~~~
      |                        |
      |                        int (*)(int)
/nix/store/drff9kypqgc8b4jzg3m17n5si46sffsb-glibc-2.40-66-dev/include/signal.h:88:57:
note: expected '__sighandler_t' {aka 'void (*)(int)'} but argument is of type 'int (*)(int)'
   88 | extern __sighandler_t signal (int __sig, __sighandler_t __handler)
      |                                          ~~~~~~~~~~~~~~~^~~~~~~~~
avoffset.c:35:1: note: 'handler' declared here
   35 | handler(signo)
      | ^~~~~~~
/nix/store/drff9kypqgc8b4jzg3m17n5si46sffsb-glibc-2.40-66-dev/include/signal.h:72:16:
note: '__sighandler_t' declared here
   72 | typedef void (*__sighandler_t) (int);
      |                ^~~~~~~~~~~~~~
avoffset.c:69:25: error: passing argument 2 of 'signal' from incompatible
pointer type [-Wincompatible-pointer-types]
   69 |         signal(SIGSEGV, handler);
      |                         ^~~~~~~
      |                         |
      |                         int (*)(int)
```