ctranslate2: fix build with gcc15
- add rebased patch from merged `cxxopts` PR that adds missing
`#include <cstdint>`:
https://www.github.com/jarro2783/cxxopts/pull/438
https://github.com/jarro2783/cxxopts/commit/63d1b65a694cfceafc20863afa75df49dfbe6b2a

Patch from commit does not apply with `fetchpatch` because other
includes below changed.

Fixes build failure with gcc15:
```
In file included from /build/source/cli/translator.cc:4:
/build/source/cli/../third_party/cxxopts/include/cxxopts.hpp:85:5:
error: 'uint8_t' does not name a type
   85 |     uint8_t major, minor, patch;
      |     ^~~~~~~
/build/source/cli/../third_party/cxxopts/include/cxxopts.hpp:58:1:
note: 'uint8_t' is defined in header '<cstdint>'; this is probably
fixable by adding '#include <cstdint>'
   57 | #    include <optional>
  +++ |+#include <cstdint>
```