djbdns: fix build with gcc15
- add `-std=gnu17` to `NIX_CFLAGS_COMPILE`, upstream had no updates
since package init in 2017

Fix build failure with gcc15:
```
In file included from dnscache-conf.c:16:
exit.h:4:13: error: conflicting types for '_exit'; have 'void(void)'
    4 | extern void _exit();
      |             ^~~~~
In file included from dnscache-conf.c:1:
/nix/store/drff9kypqgc8b4jzg3m17n5si46sffsb-glibc-2.40-66-dev/include/unistd.h:624:13:
note: previous declaration of '_exit' with type 'void(int)'
  624 | extern void _exit (int __status) __attribute__ ((__noreturn__));
      |             ^~~~~
dnscache-conf.c: In function 'main':
dnscache-conf.c:141:30: error: passing argument 2 of 'buffer_init' from
incompatible pointer type [-Wincompatible-pointer-types]
  141 |   buffer_init(&ssrootservers,buffer_unixread,fdrootservers,rootserversbuf,sizeof rootserversbuf);
      |                              ^~~~~~~~~~~~~~~
      |                              |
      |                              int (*)(int,  char *, unsigned int)
In file included from dnscache-conf.c:10:
buffer.h:16:34: note: expected 'int (*)(void)' but argument is of type
'int (*)(int,  char *, unsigned int)'
   16 | extern void buffer_init(buffer *,int (*)(),int,char *,unsigned int);
      |                                  ^~~~~~~~~
buffer.h:50:12: note: 'buffer_unixread' declared here
   50 | extern int buffer_unixread(int,char *,unsigned int);
      |            ^~~~~~~~~~~~~~~
dnscache-conf.c:168:3: error: too many arguments to function '_exit';
expected 0, have 1
  168 |   _exit(0);
      |   ^~~~~ ~
exit.h:4:13: note: declared here
    4 | extern void _exit();
      |             ^~~~~
```