llvmPackages_18.lldb: fix build with gcc15
- add patch from upstream commit that was not backported to llvm_18:

https://github.com/llvm/llvm-project/commit/bb59f04e7e75dcbe39f1bf952304a157f0035314
Fixes errors with gcc15:
/build/lldb-src-18.1.8/lldb/include/lldb/Utility/AddressableBits.h:25:27:
error: 'uint32_t' has not been declared

Cannot use `fetchpatch` because patch does not apply on llvm_18.