cron: fix build with gcc15
- add `-std=gnu17` to `env.NIX_CFLAGS_COMPILE`, upstream had no
updates since 2004

Fixes build failure with gcc15:
```
entry.c: In function 'load_entry':
entry.c:394:18: error: too many arguments to function 'error_func';
expected 0, have 1
  394 |                 (*error_func)(ecodes[(int)ecode]);
      |                 ~^~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~
```