llvmPackages_18.llvm: fix build with gcc15
- add combined patch from 2 upstream commits that were not backported
to llvm_18:

https://github.com/llvm/llvm-project/commit/8f39502b85d34998752193e85f36c408d3c99248
Fixes error with gcc15:
/build/llvm-src-18.1.8/llvm/lib/Target/AMDGPU/MCTargetDesc/AMDGPUMCTargetDesc.h:44:43:
error: 'uint8_t' has not been declared

https://github.com/llvm/llvm-project/commit/7abf44069aec61eee147ca67a6333fc34583b524
Fixes error with gcc15:
/build/llvm-src-18.1.8/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.h:86:50:
error: 'uint64_t' has not been declared

Cannot use `fetchpatch` because second patch does not apply on llvm_18.
So vendor combined patch from 2 commits.