sharutils: fix build with gcc15
- add "-std=gnu17" to `env.NIX_CFLAGS_COMPILE`

Upstream had last version update in 2015, repo has only 7 extra
commits after that with latest one in 2021.

Fedora and some distros opted for 3 big patches with fixes instead:
https://src.fedoraproject.org/rpms/sharutils/c/add972fbb1a9bd6dc4f5cf3272ebd2290e73e0cb

Fixes build failure with gcc15:
```
In file included from autoopts/project.h:30,
                 from libopts.c:2:
./compat/compat.h:188:19: error: cannot use keyword 'false' as
enumeration constant
  188 |    typedef enum { false = 0, true = 1 } _Bool;
      |                   ^~~~~
./compat/compat.h:188:19: note: 'false' is a keyword with '-std=c23'
onwards
./compat/compat.h:188:41: error: expected ';', identifier or '('
before '_Bool'
  188 |    typedef enum { false = 0, true = 1 } _Bool;
      |                                         ^~~~~
./compat/compat.h:188:41: warning: useless type name in empty
declaration
```