taskwarrior2: fix build with gcc15
- add patch from merged upstream PR:
https://www.github.com/GothenburgBitFactory/libshared/pull/71
https://github.com/GothenburgBitFactory/libshared/commit/bde76fb717c8e56e5859472ba1e890abc5b94e63

Fixes build failure with gcc15:
```
In file included from /build/source/src/Task.h:35,
                 from /build/source/src/columns/Column.h:33,
                 from /build/source/src/columns/ColTypeString.h:31,
                 from /build/source/src/columns/ColDescription.h:30,
                 from /build/source/src/columns/ColDescription.cpp:28:
/build/source/src/libshared/src/JSON.h:149:36: error: 'uint64_t' has not
been declared
  149 |       virtual void eventValueUint (uint64_t) {}
      |                                    ^~~~~~~~
/build/source/src/libshared/src/JSON.h:34:1: note: 'uint64_t' is
defined in header '<cstdint>'; this is probably fixable by
adding '#include <cstdint>'
   33 | #include <Pig.h>
  +++ |+#include <cstdint>
   34 |
```