opencc: fix build with gcc15
- add patch from merged upstream PR (no tag with it at the moment),
that adds missing `#include <cstdint>`:
https://www.github.com/BYVoid/OpenCC/pull/934
https://github.com/BYVoid/OpenCC/commit/72cae18cfe4272f2b11c9ec1c44d6af7907abcab

Fixes build failure with gcc15:
```
In file included from /build/source/src/SerializedValues.cpp:23:
/build/source/src/SerializedValues.hpp:47:36: error: 'uint16_t' was not
declared in this scope
   47 |                        std::vector<uint16_t>* valueBytes,
      |                                    ^~~~~~~~
/build/source/src/SerializedValues.hpp:23:1: note: 'uint16_t' is defined
in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
   22 | #include "SerializableDict.hpp"
  +++ |+#include <cstdint>
   23 |
```