bazel_7: fix build with gcc15
- add patch from merged upstream commit that adds missing
`#include <cstdint>`:
https://github.com/bazelbuild/bazel/commit/1d206cac050b6c7d9ce65403e6a9909a49bfe4bc

Fixes build failure with gcc15:
```
In file included from src/main/cpp/archive_utils.cc:14:
./src/main/cpp/archive_utils.h:34:9: error: 'uint64_t' does not name a type
   34 |   const uint64_t millis;
      |         ^~~~~~~~
./src/main/cpp/archive_utils.h:23:1: note: 'uint64_t' is defined in
header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
   22 | #include "src/main/cpp/util/logging.h"
  +++ |+#include <cstdint>
   23 |
```