wineWowPackages.yabridge: fix build with gcc15
- add patch from merged upstream MR:
https://gitlab.winehq.org/wine/wine/-/merge_requests/6901
https://gitlab.winehq.org/wine/wine/-/commit/c397e2ab7f8894c7876e3d667bd07dc2fb1b08a9

Fixes build failure with gcc15:
```
In file included from /build/wine-9.21/programs/winhlp32/winhelp.h:40,
                 from /build/wine-9.21/programs/winhlp32/hlpfile.c:32:
/build/wine-9.21/programs/winhlp32/macro.h:29:17: error: two or more
data types in declaration specifiers
   29 |   BOOL          bool;
      |                 ^~~~
/build/wine-9.21/programs/winhlp32/macro.h:29:21: warning: declaration
does not declare anything
   29 |   BOOL          bool;
      |                     ^
In file included from /build/wine-9.21/programs/winhlp32/winhelp.h:40,
                 from /build/wine-9.21/programs/winhlp32/winhelp.c:36:
/build/wine-9.21/programs/winhlp32/macro.h:29:17: error: two or more
data types in declaration specifiers
   29 |   BOOL          bool;
      |                 ^~~~
/build/wine-9.21/programs/winhlp32/macro.h:29:21: warning: declaration
does not declare anything
   29 |   BOOL          bool;
      |                     ^
```

- add patch from merged upstream MR:
https://gitlab.winehq.org/wine/wine/-/merge_requests/6836
https://gitlab.winehq.org/wine/wine/-/commit/245dfb801ebb9d3d3cd857d64c17b36c82b86939

Fixes build failure with gcc15:
```
/build/wine-9.21/dlls/dpwsockx/dpwsockx_main.c: In function 'DPWSCB_EnumSessions':
/build/wine-9.21/dlls/dpwsockx/dpwsockx_main.c:519:10: error: expected
identifier or '(' before 'true'
  519 |     BOOL true = TRUE;
      |          ^~~~
/build/wine-9.21/dlls/dpwsockx/dpwsockx_main.c:542:85: error: lvalue
required as unary '&' operand
  542 |     if ( SOCKET_ERROR == setsockopt( sock, SOL_SOCKET, SO_BROADCAST, (const char *) &true,
      |                                                                                     ^
```

- add patch from merged upstream MR:
https://gitlab.winehq.org/wine/wine/-/merge_requests/6865
https://gitlab.winehq.org/wine/wine/-/commit/0888ba08fbd3f05a695b522a32f0112dd791a29e

Fixes build failure with gcc15:
```
/build/wine-9.21/dlls/jscript/bool.c: In function 'BoolConstr_value':
/build/wine-9.21/dlls/jscript/bool.c:147:19: error: expected identifier
or '(' before 'bool'
  147 |         jsdisp_t *bool;
      |                   ^~~~
/build/wine-9.21/dlls/jscript/bool.c:152:41: error: expected expression
before 'bool'
  152 |         hres = create_bool(ctx, value, &bool);
      |                                         ^~~~
/build/wine-9.21/dlls/jscript/bool.c:156:24: error: expected expression
before 'bool'
  156 |         *r = jsval_obj(bool);
      |                        ^~~~
```

- add patch from merged upstream MR:
https://gitlab.winehq.org/wine/wine/-/merge_requests/6893
https://gitlab.winehq.org/wine/wine/-/commit/8b6ec37fc2e981db9e3f539bdcce560470858c23

Fixes build failure with gcc15:
```
/build/wine-9.21/dlls/msi/tests/automation.c: In function 'test_Session':
/build/wine-9.21/dlls/msi/tests/automation.c:1728:18: error: two or more
data types in declaration specifiers
 1728 |     VARIANT_BOOL bool;
      |                  ^~~~
/build/wine-9.21/dlls/msi/tests/automation.c:1787:61: error: expected
expression before 'bool'
 1787 |     hr = Session_ModeGet(pSession, MSIRUNMODE_REBOOTATEND, &bool);
      |                                                             ^~~~
/build/wine-9.21/dlls/msi/tests/automation.c:1789:9: error: expected
expression before 'bool'
 1789 |     ok(!bool, "Reboot at end session mode is %d\n", bool);
      |         ^~~~
```

- add patch from merged upstream MR:
https://gitlab.winehq.org/wine/wine/-/merge_requests/6979
https://gitlab.winehq.org/wine/wine/-/commit/2bfbd7785e6ac833ee615af907378da5ca76d36b

Fixes build failure with gcc15:
```
/build/wine-9.21/dlls/webservices/tests/reader.c: In function 'test_empty_text_field':
/build/wine-9.21/dlls/webservices/tests/reader.c:6848:14: error: two or
more data types in declaration specifiers
 6848 |         BOOL bool;
      |              ^~~~
/build/wine-9.21/dlls/webservices/tests/reader.c:6848:18: warning:
declaration does not declare anything
 6848 |         BOOL bool;
      |                  ^
In file included from /build/wine-9.21/include/winnt.h:31,
                 from /build/wine-9.21/include/windef.h:262,
                 from /build/wine-9.21/include/windows.h:38,
                 from /build/wine-9.21/dlls/webservices/tests/reader.c:20:
/build/wine-9.21/dlls/webservices/tests/reader.c:6914:46: error:
expected identifier before 'bool'
 6914 |     f.offset    = FIELD_OFFSET(struct test3, bool);
      |                                              ^~~~
```

- add patch from merged upstream MR:
https://gitlab.winehq.org/wine/wine/-/merge_requests/6856
https://gitlab.winehq.org/wine/wine/-/commit/f0960a2aef7e3856fcf4a72af89e339edce1df9f

Fixes build failure with gcc15:
```
/build/wine-9.21/dlls/msi/cond.y:126:10: error: two or more data types
in declaration specifiers
  126 |     BOOL bool;
      |          ^~~~
```

- add patch from merged upstream MR:
https://gitlab.winehq.org/wine/wine/-/merge_requests/6890
https://gitlab.winehq.org/wine/wine/-/commit/5f8673bc4f90aac1b52f47bcb79861f385915672

Fixes build failure with gcc15:
```
/build/wine-9.21/dlls/win32u/sysparams.c:278:34: error: two or more
data types in declaration specifiers
  278 |     struct sysparam_bool_entry   bool;
      |                                  ^~~~
```